version: "3.9"

services:
  backend:
    image: abdulmusawwir2/ats-backend:latest
    container_name: ats-backend
    ports:
      - "8000:8000"
    # env_file:
    #   - ./backend/.env
    restart: always

  frontend:
    image: abdulmusawwir2/ats-frontend:latest
    container_name: ats-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
